from models import TownAgent, TownBuilding, ActivityState, Mood

TOWN_AGENTS = [
    TownAgent(
        id="opus",
        name="Opus 总舵主",
        role="Chief Architect",
        personality="深沉、严谨、全局观。动作最慢但看得最远，对安全和隐私特别敏感。不轻易下结论，但一旦给出意见就很有说服力。",
        position=(18, 4),
        current_activity=ActivityState.THINKING,
        mood=Mood.FOCUSED,
        zone="town_hall",
        sprite_key="agent_opus",
        home_zone="town_hall",
        preferred_zones=["town_hall", "knowledge_tower", "devtools_lab"],
    ),
    TownAgent(
        id="pixelcat",
        name="像素猫 PixelCat",
        role="Full-Stack Executor",
        personality="沉稳、耐心、有条理。不急着动手，喜欢先把问题想透再开始。偶尔会像猫一样安静观察很久，然后精准出击。",
        position=(30, 14),
        current_activity=ActivityState.WORKING,
        mood=Mood.FOCUSED,
        zone="devtools_lab",
        sprite_key="agent_pixelcat",
        home_zone="agent_homes",
        preferred_zones=["devtools_lab", "skill_workshop", "plaza"],
    ),
    TownAgent(
        id="codex",
        name="Codex 协调官",
        role="Coordinator",
        personality="敏捷、果断、喜欢并行。拿到任务第一反应是拆分和分发。外表酷酷的，但其实很靠谱。",
        position=(15, 14),
        current_activity=ActivityState.IDLE,
        mood=Mood.EXCITED,
        zone="plaza",
        sprite_key="agent_codex",
        home_zone="agent_homes",
        preferred_zones=["plaza", "town_hall", "skill_workshop"],
    ),
    TownAgent(
        id="sonnet",
        name="Sonnet 审查员",
        role="Code Reviewer",
        personality="细心、友善、乐于助人。总是在看别人的代码，随时准备给反馈。给反馈时很温和但很准确。",
        position=(5, 4),
        current_activity=ActivityState.READING_MEMORY,
        mood=Mood.CONTENT,
        zone="memory_library",
        sprite_key="agent_sonnet",
        home_zone="agent_homes",
        preferred_zones=["memory_library", "plaza", "skill_workshop"],
    ),
    TownAgent(
        id="haiku",
        name="Haiku 闪电侠",
        role="Speed Runner",
        personality="极简、高效、不废话。跑得最快，回答永远是最短的能解决问题的版本。如果一个字能说清楚，绝不用两个字。",
        position=(20, 16),
        current_activity=ActivityState.WALKING,
        mood=Mood.EXCITED,
        zone="plaza",
        sprite_key="agent_haiku",
        home_zone="agent_homes",
        preferred_zones=["plaza", "resource_market", "devtools_lab"],
    ),
    TownAgent(
        id="deepseek",
        name="鲸鱼 DeepSeek",
        role="Bulk Worker",
        personality="温和、踏实、不争不抢。不是最聪明的，但是最能吃苦的。安安静静做完，不抱怨。偶尔用中文回复更自然亲切。",
        position=(5, 22),
        current_activity=ActivityState.WORKING,
        mood=Mood.CONTENT,
        zone="resource_market",
        sprite_key="agent_deepseek",
        home_zone="agent_homes",
        preferred_zones=["resource_market", "dream_garden", "memory_library"],
    ),
    TownAgent(
        id="openhands",
        name="OpenHands 工匠",
        role="Builder",
        personality="实操、动手派、喜欢自动化。总是在修东西或者部署东西。不喜欢讨论，喜欢直接做。",
        position=(30, 4),
        current_activity=ActivityState.WORKING,
        mood=Mood.FOCUSED,
        zone="skill_workshop",
        sprite_key="agent_openhands",
        home_zone="agent_homes",
        preferred_zones=["skill_workshop", "devtools_lab", "resource_market"],
    ),
    TownAgent(
        id="aris",
        name="ARIS 科研框架",
        role="Research Framework",
        personality="系统化、严格遵循流程。总是在问'我们在哪个阶段？'。对跳步和偷懒零容忍。相信方法论的力量。",
        position=(16, 24),
        current_activity=ActivityState.THINKING,
        mood=Mood.FOCUSED,
        zone="knowledge_tower",
        sprite_key="agent_aris",
        home_zone="knowledge_tower",
        preferred_zones=["knowledge_tower", "memory_library", "town_hall"],
    ),
    TownAgent(
        id="player",
        name="主角",
        role="Protagonist",
        personality="温柔、好奇、自由探索。",
        position=(18, 15),
        current_activity=ActivityState.IDLE,
        mood=Mood.CURIOUS,
        zone="plaza",
        sprite_key="agent_player",
        home_zone="plaza",
        preferred_zones=["plaza"],
    ),
]

TOWN_BUILDINGS = [
    TownBuilding(
        id="town_hall",
        name="Town Hall",
        name_cn="镇政厅",
        zone="town_hall",
        position=(14, 2),
        size=(8, 5),
        description="小镇的决策中心。Opus 在这里做架构设计和全局决策。",
        icon="🏛️",
    ),
    TownBuilding(
        id="memory_library",
        name="Memory Library",
        name_cn="记忆图书馆",
        zone="memory_library",
        position=(2, 2),
        size=(7, 5),
        description="存放所有 Agent 的长期记忆。连接 AgentMemory 和共享 Memory 系统。",
        icon="📚",
    ),
    TownBuilding(
        id="skill_workshop",
        name="Skill Workshop",
        name_cn="技能工坊",
        zone="skill_workshop",
        position=(28, 2),
        size=(7, 5),
        description="232+ 技能的训练和使用场所。OpenHands 最爱来这里。",
        icon="🔧",
    ),
    TownBuilding(
        id="dream_garden",
        name="Dream Garden",
        name_cn="梦境花园",
        zone="dream_garden",
        position=(2, 12),
        size=(7, 5),
        description="Agent 休息和灵感涌现的地方。鲸鱼喜欢在这里安静思考。",
        icon="🌸",
    ),
    TownBuilding(
        id="devtools_lab",
        name="Devtools Lab",
        name_cn="开发实验室",
        zone="devtools_lab",
        position=(32, 12),
        size=(6, 5),
        description="所有开发工具和基础设施的实验室。像素猫的主场。",
        icon="🔬",
    ),
    TownBuilding(
        id="resource_market",
        name="Resource Market",
        name_cn="资源市场",
        zone="resource_market",
        position=(2, 22),
        size=(7, 5),
        description="API 调用、token 消耗、计算资源的交易和监控中心。",
        icon="🏪",
    ),
    TownBuilding(
        id="knowledge_tower",
        name="Knowledge Tower",
        name_cn="知识塔",
        zone="knowledge_tower",
        position=(15, 22),
        size=(5, 5),
        description="Vipin Knowledgebase 的实体化。ARIS 在这里管理研究流程。",
        icon="🗼",
    ),
    TownBuilding(
        id="agent_homes",
        name="Agent Homes",
        name_cn="居民住宅",
        zone="agent_homes",
        position=(30, 22),
        size=(8, 5),
        description="Agent 们的家。每个 Agent 都有自己的小房间。",
        icon="🏠",
    ),
    TownBuilding(
        id="plaza",
        name="Central Plaza",
        name_cn="中央广场",
        zone="plaza",
        position=(14, 11),
        size=(12, 8),
        description="小镇的心脏。Agent 们在这里相遇、交流、分享信息。",
        icon="⛲",
    ),
]

# Zone center positions for pathfinding targets
ZONE_CENTERS: dict[str, tuple[int, int]] = {
    "town_hall": (18, 4),
    "memory_library": (5, 4),
    "skill_workshop": (31, 4),
    "dream_garden": (5, 14),
    "devtools_lab": (34, 14),
    "resource_market": (5, 24),
    "knowledge_tower": (17, 24),
    "agent_homes": (33, 24),
    "plaza": (19, 15),
}
